version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ticket_booking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ticket_booking
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticket_booking_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  ticket_booking_network:
    driver: bridge

volumes:
  postgres_data: 